name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # 监听 'main' 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Generate index.html
      run: node generate-index.js  # 生成 index.html 的脚本

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update generated HTML files"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # 部署到 'gh-pages' 分支
        publish_dir: ./  # 发布目录为根目录（包含生成的 HTML 文件）


